#!/bin/bash

echo "what is your device name?"

read name
user=$(whoami)
date=$(date)
whereami=$(pwd)
internet=$(netstat)
system_info=$(uname -a)

echo "hello $name"

sleep 3

echo "how is your battary health $name"

sleep 2

echo "how is your cpu health $name"

sleep 2

echo "RAM is overloaded $name"

sleep 2

echo "you are in current $user"

sleep 2

echo "todays $date"

sleep 2

echo "working directory $whereami"

sleep 2

echo "network status $internet"

sleep 2

echo "my system information $system_info"
